shop/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index_n"),
    path("profile/", views.profilis, name='user_profile_n'),
    path("administrator/", views.administrator_page, name='administrator_n'),
    ##
    path("administrator/add_category", views.ItemCategoryCreateView.as_view(), name='add_category_n'),
    path("administrator/<int:pk>/update_category", views.ItemCategoryUpdateView.as_view(), name='update_category_n'),
    path("administrator/<int:pk>/delete_category", views.ItemCategoryDeleteView.as_view(), name='delete_category_n'),
    ##
    path("administrator/add_item_model", views.ItemModelCreateView.as_view(), name='add_item_model_n'),
    path("administrator/<int:pk>/update_item_model", views.ItemModelUpdateView.as_view(), name='update_item_model_n'),
    path("administrator/<int:pk>/delete_item_model", views.ItemModelDeleteView.as_view(), name='delete_item_model_n'),
    path("view_items_models_list/", views.ItemModelListView.as_view(), name='view_items_models_list_n'),
    path("view_item_model_detail/<int:pk>", views.ItemModelDetailView.as_view(), name='view_item_model_detail_n'),
    ##
    path("administrator/add_item", views.ItemCreateView.as_view(), name='add_item_n'),
    path("administrator/<uuid:pk>/update_item", views.ItemUpdateView.as_view(), name='update_item_n'),
    path("administrator/<uuid:pk>/delete_item", views.ItemDeleteView.as_view(), name='delete_item_n'),
    path("administrator/view_items", views.ItemView.as_view(), name='view_items_list_n'),
    path("administrator/view_orders", views.AdministratorOrderListView.as_view(), name='view_order_list_n'),
    path("administrator/view_orders/<int:pk>", views.AdministratorOrderDetailView.as_view(), name='view_order_detail_n'),
    ##
    path("cart/", views.user_cart_view, name='user_cart_n'),
    path("add_to_cart/", views.add_item_to_cart, name='add_item_to_cart_n'),
    path("remove_from_cart/", views.remove_item_from_cart, name='remove_item_from_cart_n'),
    path("cart/increase/", views.increase_item_count, name='increase_quantity_n'),
    path("cart/decrease/", views.decrease_item_count, name='decrease_quantity_n'),
    ##
    path("cart/submit", views.submit_order_by_user, name='submit_order_by_user_n'),
    path("cart/user_orders", views.UserOrderListView.as_view(), name='view_order_by_user_list_n'),


]

urlpatterns = urlpatterns + [
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/register/", views.register, name='register_n'),

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/", include("shop.urls")),
    path("", RedirectView.as_view(url="app/", permanent=True)),
] + static (settings.STATIC_URL, document_root = settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
from PIL import Image
from .my_utils import generate_thumbnail

# Item = Product, can't change now! naming mistake

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")
    adress = models.CharField("shipping details", max_length=150, blank=True, null=True)

    def __str__(self):
        return f" logged as: {self.user.username}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        thumb_size = 150
        img_thumb = generate_thumbnail(img, thumb_size, )
        img_thumb.save(self.photo.path)


class ItemCategory(models.Model):
    item_category = models.CharField("Item category", max_length=30, help_text="shop item category name")

    def __str__(self):
        return f"{self.item_category}"

class ItemModel(models.Model):
    item_model_name = models.CharField("Item model name", max_length=30, help_text="shop item category name")
    category_id = models.ManyToManyField("ItemCategory", help_text="Item category")
    price = models.FloatField("Item price", default="0.00")
    photo = models.ImageField(default="item_pics/default.jpg", upload_to="item_pics", null=True)

    def save(self, *args, **kwargs):
        self.price = round(self.price, 2)
        super(ItemModel, self).save(*args, **kwargs)
        img = Image.open(self.photo.path)
        thumb_size = 600
        img_thumb = generate_thumbnail(img, thumb_size)
        img_thumb.save(self.photo.path)

    @property
    def items_left_a(self):
        return len(self.item_set.filter(status='a'))

    @property
    def items_left(self):
        return len(self.item_set.all())



    def __str__(self):
        return f"{self.item_model_name}"


class Item(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    item_model_id = models.ForeignKey('ItemModel', on_delete=models.CASCADE, null=True, blank=True)


    ITEM_STATUS = (
        ('u', 'Unavailable'),
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('s', 'Sold'),
    )

    status = models.CharField(
        "Status",
        max_length=1,
        choices=ITEM_STATUS,
        blank=True,
        default='u',
        help_text="Item status"
    )

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)


    @property
    def cart_total(self):
        items = [item for item in self.cartitem_set.all()]
        return sum([(i.item_model_id.price * i.calculated_quantity) for i in items])

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    order_comment = models.TextField("Comment", max_length=1000, null=True, blank=True)




class CartItem(models.Model):
    item_model_id = models.ForeignKey('ItemModel', on_delete=models.CASCADE, null=True, blank=True)
    cart_id = models.ForeignKey('Cart', on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField("quantity", default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    order_id = models.ForeignKey('Order', on_delete=models.SET_NULL, null=True, blank=True)


    @property
    def calculated_quantity(self):
        if self.quantity > self.item_model_id.items_left_a:
            return self.item_model_id.items_left_a
        elif self.quantity < 0:
            return 0
        else:
            return self.quantity

    @property
    def calculated_price(self):
        return self.calculated_quantity * self.item_model_id.price

    def save(self, *args, **kwargs):
        if self.quantity > self.item_model_id.items_left_a:
            self.quantity = self.item_model_id.items_left_a
        elif self.quantity < 0:
            self.quantity = 0
        super(CartItem, self).save(*args, **kwargs)

    def __str__(self):
        return f"item's cart id: {self.cart_id}"

shop/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .my_utils import password_check
from django.contrib.auth.decorators import login_required


from .forms import UserProfileUpdateForm, UserUpdateForm, ItemCategoryCreateForm, ItemModelCreateForm, \
    ItemCreateForm
from .models import ItemCategory, ItemModel, Item, Cart, CartItem, Order

# html vistiek reikia pakeisti
admin_group_name = 'shop_admin'


def index(request):
    return redirect('view_items_models_list_n')

@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            check_result = password_check(password, username)
            if check_result == 'ok':
                if User.objects.filter(username=username).exists():
                    messages.error(request, "Username %s ir already exists" % username)
                    return redirect('register_n')
                else:
                    # ar nera sistemoj tokio pat vartotojo email
                    if User.objects.filter(email=email).exists():
                        messages.error(request, f"Vartotojas su email '{email}' jau egzistuoja")
                        return redirect('register_n')
                    else:
                        User.objects.create_user(username=username, email=email, password=password)
                        messages.info(request, f"Vartotojas {username} užregistruotas !")
                        return redirect('login')
            else:
                messages.error(request, f"error: {check_result}")
                return redirect('register_n')
        else:
            messages.error(request, f"Slaptažodžiai turi sutapti !")
            return redirect('register_n')

    return render(request, "registration/register.html")


@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('user_profile_n')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = UserProfileUpdateForm(instance=request.user.userprofile)

    data = {
        'u_form_cntx': u_form,
        'p_form_cntx': p_form,
    }
    return render(request, "user_profile.html", context=data)


@login_required
def administrator_page(request):
    categories_num = ItemCategory.objects.all().count()
    categories_list = ItemCategory.objects.all()
    item_models_list = ItemModel.objects.all()
    item_list = ItemModel.objects.all()

    data = {
        'categories_num_cntx': categories_num,
        'categories_list_cntx': categories_list,
        'item_models_list_cntx': item_models_list,
        'item_list_cntx': item_list,
    }
    if admin_group_name in [group.name for group in request.user.groups.all()]:
        return render(request, 'administrator_page.html', context=data)
    else:
        return redirect('index_n')


# Item Category

class ItemCategoryCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = ItemCategory
    success_url = "/app/administrator"
    template_name = "add_item_category.html"
    form_class = ItemCategoryCreateForm

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        print(f"formos naudotojas: {form.instance.form_user}")
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemCategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = ItemCategory
    success_url = "/app/administrator"
    template_name = "add_item_category.html"
    form_class = ItemCategoryCreateForm

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        print(f"formos naudotojas: {form.instance.form_user}")
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemCategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = ItemCategory
    success_url = "/app/administrator"
    template_name = "delete_item_category.html"

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


# Item Model

class ItemModelCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = ItemModel
    form_class = ItemModelCreateForm
    success_url = "/app/administrator"
    template_name = "add_item_model.html"

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemModelUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = ItemModel
    form_class = ItemModelCreateForm
    success_url = "/app/administrator"
    template_name = "add_item_model.html"

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemModelDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = ItemModel
    success_url = "/app/administrator"
    template_name = "delete_item_model.html"

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemModelListView(generic.ListView):
    model = ItemModel
    context_object_name = 'itemmodel_list'
    template_name = 'view_items_models_list.html'
    paginate_by = 6

    def get_queryset(self):
        query = ItemModel.objects.order_by('item_model_name')
        return query



class ItemModelDetailView(generic.DetailView):
    model = ItemModel
    context_object_name = 'itemmodel'
    template_name = 'view_item_model_detail.html'


# Item

class ItemCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    model = Item
    form_class = ItemCreateForm
    success_url = "/app/administrator"
    template_name = "add_item.html"

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False

class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Item
    form_class = ItemCreateForm
    success_url = "/app/administrator/view_items"
    template_name = "add_item.html"

    def form_valid(self, form):
        form.instance.form_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False

class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Item
    success_url = "/app/administrator/view_items"
    template_name = "delete_item.html"

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class ItemView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = Item
    context_object_name = 'item_list'
    template_name = 'view_items_list.html'
    paginate_by = 5

    def get_queryset(self):
        query = Item.objects.order_by('item_model_id')
        return query

    def test_func(self):
        user_groups_list = [group.name for group in self.request.user.groups.all()]
        if admin_group_name in user_groups_list:
            return True
        else:
            return False


class AdministratorOrderListView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = Order
    context_object_name = 'order_list'
    template_name = 'view_order_list.html'
    #paginate_by = 5

    def get_queryset(self):
        query = Order.objects.order_by('date_created')
        return query

    def test_func(self):

shop/templates/add_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New item category</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>


{% endblock %}

shop/templates/add_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container p2">
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add item</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>



{% endblock %}

shop/templates/add_item_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New item category</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>
{% include "view_item_category_list.html" %}


{% endblock %}

shop/templates/add_item_model.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container p2">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New shop item</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>



{% endblock %}

shop/templates/administrator_page.html
{% extends "base.html" %}
{% block content %}

<div class="container ">
    <div class="d-inline-flex flex-row">
        <a class="btn btn-sm btn-primary btn-dark m-1" href="{% url 'add_category_n' %}">ADD CATEGORY</a>
        <a class="btn btn-sm btn-primary btn-dark m-1" href="{% url 'add_item_model_n' %}">ADD SHOP ITEM MODEL</a>
        <a class="btn btn-sm btn-primary btn-dark m-1" href="{% url 'add_item_n' %}">ADD SHOP ITEM</a>
        <a class="btn btn-sm btn-primary btn-dark m-1" href="{% url 'view_items_list_n' %}">VIEW ITEMS INSTANCES</a>
        <a class="btn btn-sm btn-primary btn-dark m-1" href="{% url 'view_order_list_n' %}">VIEW ORDERS LIST</a>
    </div>
</div>

<div class="container mt-5">

    <div class="row row-cols-2">
        <div class="col">
            <h5>CATEGORIES</h5>
        </div>
        <div class="col">
            <h5>OPTIONS</h5>
        </div>
        {% for category_obj in categories_list_cntx %}
        <div class="col">
            {{ category_obj }}
        </div>

        <div class="col">
            <a class="btn btn-outline-dark m-1" href="{% url 'update_category_n' category_obj.id %}"
               role="button">Edit</a>
            <a class="btn btn-outline-dark m-1" href="{% url 'delete_category_n' category_obj.id %}"
               role="button">Delete</a>
        </div>
        {% endfor %}

    </div>
</div>


<div class="container mt-5">


    <div class="row row-cols-6">
        <div class="col">
            <h5>PICTURE</h5>
        </div>
        <div class="col">
            <h5>ITEM MODELS</h5>
        </div>
        <div class="col">
            <h5>ITEM PRICE</h5>
        </div>
        <div class="col">
            <h5>AVAILABLE/TOTAL</h5>
        </div>
        <div class="col">
            <h5>CATEGORIES</h5>
        </div>
        <div class="col">
            <h5>OPTIONS</h5>
        </div>

        {% for item_model_obj in item_models_list_cntx %}
        <div class="col">
            <img src="{{ item_model_obj.photo.url }}" class="card-img-top" style="max-width: 50px;  height: auto;">
        </div>
        <div class="col">
            {{ item_model_obj.item_model_name }}
        </div>
        <div class="col">
            {{ item_model_obj.price }}
        </div>
        <div class="col">
            {{ item_model_obj.items_left_a }} / {{ item_model_obj.items_left }}
        </div>

        <div class="col d-inline-flex flex-row">
            {% for category_obj in item_model_obj.category_id.all %}
            <div class="m-1">{{ category_obj }}</div>
            {% endfor %}
        </div>
        <div class="col d-inline-flex flex-row">
            <a class="btn btn-outline-dark m-1" href="{% url 'update_item_model_n' item_model_obj.id %}"
               role="button">Edit</a>
            <a class="btn btn-outline-dark m-1" href="{% url 'delete_item_model_n' item_model_obj.id %}"
               role="button">DELETE</a>
        </div>
        {% endfor %}

    </div>
</div>


<br>
</div>


{% endblock %}

shop/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>miniapp</title>
    {% load static %}
</head>
<body>

{% include "navbar_1.html" %}


{% if messages %}

{% for message in messages %}
<div class="container">
    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

{% block content %}{% endblock %}


<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<!--
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
-->
<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>
</html>

shop/templates/delete_item_category.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">DELETE CATEGORY</legend>
            <h2>ARE YOU SURE?</h2>
            <p> Delete category: {{ object.item_category }}</p>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outlane-danget" type="submit">DELETE</button>
            <a href="{{ view.get_success_url }}" class="btn btn-outline-secondary">CANCEL</a>


        </div>
    </form>
</div>


{% endblock %}

shop/templates/user_cart.html
{% extends "base.html" %}
{% block content %}


{% if user.is_authenticated %}

<div class="container mt-5">
    <div class="row row-cols-6">

        {% for cart_item_obj in cart_cntx.cartitem_set.all %}
        <div class="col">
            {{ cart_item_obj.item_model_id.item_model_name }}
        </div>
        <div class="col">
            <img src="{{ cart_item_obj.item_model_id.photo.url }}" class="card-img-top"
                 style="max-width: 50px;  height: auto;">
        </div>
        <div class="col">
            {{ cart_item_obj.calculated_price }}
        </div>
        <div class="col d-inline-flex flex-row">
            {% for category_obj in cart_item_obj.item_model_id.category_id.all %}
            <div class="m-1">{{ category_obj }}</div>
            {% endfor %}
        </div>

        <div class="col d-inline-flex flex-row align-items-center">

            <form action="{% url 'decrease_quantity_n' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark m-1" name="decrease_quantity"
                        value="{{ cart_item_obj.id }}">-
                </button>
            </form>

            <div class="m-1">{{ cart_item_obj.calculated_quantity }}</div>

            <form action="{% url 'increase_quantity_n' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark m-1" name="increase_quantity"
                        value="{{ cart_item_obj.id }}">+
                </button>
            </form>

        </div>
        <div class="col">
            <form action="{% url 'remove_item_from_cart_n' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark m-1" name="item_to_delete"
                        value="{{ cart_item_obj.id }}">Remove
                </button>
            </form>
        </div>
        {% endfor %}

    </div>
    <hr>
    <div><h5>Total: {{ user.cart.cart_total }} </h5></div>
    <div class="col">
        <form action="{% url 'submit_order_by_user_n' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-dark m-1" name="cart_to_submit" value="{{ cart_item_obj.id }}">SUBMIT ORDER
            </button>
        </form>
    </div>
    <div class="col">
        {% for order in user.order_set.all %}
        {{ order.id }}<br>
        {% endfor %}
    </div>
</div>


{% else %}
403 Forbidden
{% endif %}


{% endblock %}

shop/templates/view_items_list.html
{% extends "base.html" %}
{% block content %}

{% for group in user.groups.all %}
{% if group.name == 'shop_admin' %}


<div class="row">
    <div class="col-md-6 m-auto">
        <nav>
            {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}"
                    >&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
                {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{page_obj.next_page_number}}" class="page-link"
                    >&raquo;</a
                    >
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </nav>
    </div>
</div>


<div class="container mt-5">
    <div class="row row-cols-5">

        <div class="col">
            <h4>Item status</h4>
        </div>
        <div class="col">
            <h4>Item model</h4>
        </div>
        <div class="col col-4">
            <h4>Item ID</h4>
        </div>
        <div class="col">
            <h4>Options</h4>
        </div>

        {% for item_obj in item_list %}
        <div class="col">
            {{ item_obj.get_status_display }}
        </div>
        <div class="col">
            {{ item_obj.item_model_id.item_model_name }}
        </div>
        <div class="col col-4"">
            {{ item_obj.id }}
        </div>
        <div class="col">
            <a class="btn btn-outline-dark m-1" href="{% url 'update_item_n' item_obj.id %}"
               role="button">Edit</a>
            <a class="btn btn-outline-dark m-1" href="{% url 'delete_item_n' item_obj.id %}"
               role="button">Delete</a>
        </div>
        {% endfor %}
    </div>
</div>


{% endif %}
{% endfor %}


{% endblock %}